<?php

return [
    [
        'name' => '首页',
        'uri' => 'backend.index',
        'permission' => '',
        'icon' => 'fa fa-fw fa-dashboard',
        'parent_id' => '0',
        'label' => '', 'target' => '',
        'sort' => 10000000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => '商品',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa iconfont icon-goods',
        'parent_id' => '0',
        'label' => '', 'target' => '',
        'sort' => 9000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '商品管理',
                'uri' => 'backend.products.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '分类管理',
                'uri' => 'backend.product.categories.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '品牌管理',
                'uri' => 'backend.product.brands.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '规格管理',
                'uri' => 'backend.product.specifications.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '售后服务',
                'uri' => 'backend.after-services.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '回收站',
                'uri' => 'backend.product.recycles.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '订单',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa iconfont icon-order',
        'label' => '', 'target' => '',
        'sort' => 8000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '订单列表',
                'uri' => 'backend.orders.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '商家',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa iconfont icon-shoplight',
        'label' => '', 'target' => '',
        'sort' => 7000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '店铺列表',
                'uri' => 'backend.shops.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '店铺等级',
                'uri' => 'backend.shop-grades.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'shop_grades', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '店铺类型',
                'uri' => 'backend.shop-types.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'shop_types', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '商家管理',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => '店铺分类',
                        'uri' => '',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => '', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '财务管理',
                        'uri' => '',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => '', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '保证金管理',
                        'uri' => '',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => '', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [
                            [
                                'name' => '期限管理',
                                'uri' => '',
                                'permission' => '',
                                'icon' => '',
                                'parent_id' => '',
                                'label' => '', 'target' => '',
                                'sort' => 1000,
                                'status' => true,
                                'created_at' => now(),
                                'updated_at' => now(),
                            ], [
                                'name' => '保证金设置',
                                'uri' => '',
                                'permission' => '',
                                'icon' => '',
                                'parent_id' => '',
                                'label' => '', 'target' => '',
                                'sort' => 1000,
                                'status' => true,
                                'created_at' => now(),
                                'updated_at' => now(),
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'name' => '会员',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-user',
        'label' => 'users_group', 'target' => '',
        'sort' => 6000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '会员管理',
                'uri' => 'backend.users.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'users', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '会员账户',
                'uri' => 'backend.user.accounts.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'user_accounts', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '积分规则',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '会员提现申请',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '实名认证',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '会员等级',
                'uri' => 'backend.user.grades.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'user_grades', 'target' => '',
                'sort' => 900,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '提现申请',
                'uri' => 'backend.user.cash-withdrawals.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'user_cash_withdrawals', 'target' => '',
                'sort' => 800,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '充值卡管理',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '预存款管理',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '文章',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-book',
        'parent_id' => '',
        'label' => 'articles_group', 'target' => '',
        'sort' => 5900,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '文章列表',
                'uri' => 'backend.articles.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'articles', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '文章分类',
                'uri' => 'backend.article-categories.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '运营',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-flag',
        'label' => 'marketing_group', 'target' => '',
        'sort' => 5000,
        'status' => false,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '营销',
                'uri' => '',
                'permission' => '',
                'icon' => 'fa fa-fw fa-fire',
                'parent_id' => '',
                'label' => 'marketing', 'target' => '',
                'sort' => 1000,
                'status' => false,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => '促销工具',
                        'uri' => '',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => '', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '运营工具',
                        'uri' => '',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => '', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '互动营销',
                        'uri' => '',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => '', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '新客满减',
                        'uri' => '',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => '', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                ],
            ], [
                'name' => '活动列表',
                'uri' => 'backend.activities.index',
                'permission' => '',
                'icon' => 'fa fa-fw fa-gift',
                'parent_id' => '',
                'label' => 'activities', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [],
            ], [
                'name' => '统计报表',
                'uri' => '',
                'permission' => '',
                'icon' => 'fa fa-fw fa-line-chart',
                'parent_id' => '',
                'label' => '', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => '销售统计',
                        'uri' => 'backend.stats.sales.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'stats_sales', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '会员统计',
                        'uri' => 'backend.stats.users.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'stats_users', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '订单统计',
                        'uri' => 'backend.stats.orders.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'stats_orders', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '店铺统计',
                        'uri' => 'backend.stats.shops.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'stats_shops', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '商品分析',
                        'uri' => 'backend.stats.orders.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'stats_orders', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                ],
            ],
        ],
    ],
    [
        'name' => '网站',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-sitemap',
        'label' => '', 'target' => '',
        'sort' => 4000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '基本设置',
                'uri' => 'backend.sites.bases.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_bases', 'target' => '',
                'sort' => 10000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '广告管理',
                'uri' => 'backend.adverts.index',
                'permission' => '',
                'icon' => 'fa fa-fw fa-image',
                'parent_id' => '',
                'label' => 'adverts', 'target' => '',
                'sort' => 9600,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '导航管理',
                'uri' => 'backend.sites.navigations.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_navigations', 'target' => '',
                'sort' => 9000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '轮播图管理',
                'uri' => 'backend.sites.sliders.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_sliders', 'target' => '',
                'sort' => 8000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '链接管理',
                'uri' => 'backend.sites.links.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_links', 'target' => '',
                'sort' => 7000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '页面管理',
                'uri' => 'backend.pages.index',
                'permission' => '',
                'icon' => 'fa fa-fw fa-file-code-o',
                'parent_id' => '',
                'label' => 'pages', 'target' => '',
                'sort' => 6800,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '店铺设置',
                'uri' => 'backend.sites.shops.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_shops', 'target' => '',
                'sort' => 6600,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '主题设置',
                'uri' => 'backend.sites.themes.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_themes', 'target' => '',
                'sort' => 6000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '访问拦截',
                'uri' => 'backend.sites.intercept.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_register', 'target' => '',
                'sort' => 5500,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '注册设置',
                'uri' => 'backend.sites.register.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_register', 'target' => '',
                'sort' => 5000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '商品设置',
                'uri' => 'backend.sites.product.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_product', 'target' => '',
                'sort' => 4000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '订单设置',
                'uri' => 'backend.sites.orders.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_orders', 'target' => '',
                'sort' => 3500,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '演示数据',
                'uri' => 'backend.sites.demo-data.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'sites_demo-data', 'target' => '',
                'sort' => 3000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '全局',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-cog',
        'label' => '', 'target' => '',
        'sort' => 3500,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '短信设置',
                'uri' => 'backend.settings.sms.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'settings_sms', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '邮箱设置',
                'uri' => 'backend.settings.mail.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'settings_mail', 'target' => '',
                'sort' => 950,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '支付设置',
                'uri' => 'backend.settings.payments.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'settings_payments', 'target' => '',
                'sort' => 900,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '配送方式',
                'uri' => 'backend.settings.shippings.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'settings_shippings', 'target' => '',
                'sort' => 850,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '地区设置',
                'uri' => 'backend.settings.regions.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'settings_regions', 'target' => '',
                'sort' => 800,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '合作登录',
                'uri' => 'backend.settings.oauth.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'settings_oauth', 'target' => '',
                'sort' => 750,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => 'IP查询',
                'uri' => 'backend.settings.geoip.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'settings_geoip', 'target' => '',
                'sort' => 650,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '系统',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-gears',
        'label' => 'systems_group', 'target' => '',
        'sort' => 3000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '基本设置',
                'uri' => 'backend.systems.bases.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_bases', 'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '数据库设置',
                'uri' => 'backend.systems.databases.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_databases', 'target' => '',
                'sort' => 950,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '缓存设置',
                'uri' => 'backend.systems.caches.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_caches', 'target' => '',
                'sort' => 900,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '会话设置',
                'uri' => 'backend.systems.session.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_session', 'target' => '',
                'sort' => 850,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '队列管理',
                'uri' => 'backend.systems.queue.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_queue', 'target' => '',
                'sort' => 820,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '存储设置',
                'uri' => 'backend.systems.filesystems.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_filesystems', 'target' => '',
                'sort' => 810,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '路由设置',
                'uri' => 'backend.systems.routes.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_routes', 'target' => '',
                'sort' => 800,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '菜单管理',
                'uri' => 'backend.systems.menus.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_menus', 'target' => '',
                'sort' => 750,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '日志管理',
                'uri' => 'backend.systems.log.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_log', 'target' => '',
                'sort' => 720,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '权限管理',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_rbac_group', 'target' => '',
                'sort' => 700,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => '管理员管理',
                        'uri' => 'backend.systems.admins.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'systems_admins', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '角色管理',
                        'uri' => 'backend.systems.roles.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'systems_roles', 'target' => '',
                        'sort' => 900,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '权限管理',
                        'uri' => 'backend.systems.permissions.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'systems_permissions', 'target' => '',
                        'sort' => 800,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '安全设置',
                        'uri' => 'backend.systems.security.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'systems_security', 'target' => '',
                        'sort' => 700,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                ],
            ], [
                'name' => '开发管理',
                'uri' => '',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_dev_group', 'target' => '',
                'sort' => 660,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => 'Telescope',
                        'uri' => 'backend.systems.telescope.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'systems_telescope', 'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '字体图标',
                        'uri' => 'backend.systems.font-icon.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'systems_font_icon', 'target' => '',
                        'sort' => 800,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ], [
                        'name' => '例子管理',
                        'uri' => 'backend.examples.index',
                        'permission' => '',
                        'icon' => '',
                        'parent_id' => '',
                        'label' => 'examples', 'target' => '',
                        'sort' => 600,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ],
                ],
            ], [
                'name' => '在线更新',
                'uri' => 'backend.systems.update.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'systems_update', 'target' => '',
                'sort' => 650,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'name' => '关于我们',
                'uri' => config('app.support'),
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'about_us', 'target' => '_blank',
                'sort' => 550,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],

    [
        'name' => '终端',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-cubes',
        'label' => 'terminal_group',
        'target' => '',
        'sort' => 2000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => 'Api端',
                'uri' => '',
                'permission' => '',
                'icon' => 'fa fa-fw fa-globe',
                'label' => 'terminal_group_api',
                'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => '基本设置',
                        'uri' => 'backend.terminal.api.bases.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_api_bases',
                        'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '轮播图',
                        'uri' => 'backend.terminal.api.sliders.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_api_sliders',
                        'target' => '',
                        'sort' => 900,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '导航',
                        'uri' => 'backend.terminal.api.navigations.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_api_navigations',
                        'target' => '',
                        'sort' => 800,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '链接',
                        'uri' => 'backend.terminal.api.links.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_api_links',
                        'target' => '',
                        'sort' => 800,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '广告',
                        'uri' => 'backend.terminal.api.adverts.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_api_adverts',
                        'target' => '',
                        'sort' => 700,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '文章',
                        'uri' => 'backend.terminal.api.articles.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_api_articles',
                        'target' => '',
                        'sort' => 600,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ],
                ],
            ], [
                'name' => '手机端',
                'uri' => '',
                'permission' => '',
                'icon' => 'fa fa-fw fa-mobile',
                'label' => 'terminal_group_mobile',
                'target' => '',
                'sort' => 900,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => '基本设置',
                        'uri' => 'backend.terminal.mobile.bases.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_mobile_bases',
                        'target' => '',
                        'sort' => 1000,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '轮播图',
                        'uri' => 'backend.terminal.mobile.sliders.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_mobile_sliders',
                        'target' => '',
                        'sort' => 900,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '导航',
                        'uri' => 'backend.terminal.mobile.navigations.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_mobile_navigations',
                        'target' => '',
                        'sort' => 800,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '广告',
                        'uri' => 'backend.terminal.mobile.adverts.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_mobile_adverts',
                        'target' => '',
                        'sort' => 700,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '文章',
                        'uri' => 'backend.terminal.mobile.articles.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_mobile_articles',
                        'target' => '',
                        'sort' => 600,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ],
                ],
            ], [
                'name' => '电脑端',
                'uri' => '',
                'permission' => '',
                'icon' => 'fa fa-fw fa-desktop',
                'label' => 'terminal_group_web',
                'target' => '',
                'sort' => 800,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
                'children' => [
                    [
                        'name' => '广告',
                        'uri' => 'backend.terminal.web.adverts.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_web_adverts',
                        'target' => '',
                        'sort' => 700,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ], [
                        'name' => '文章',
                        'uri' => 'backend.terminal.web.articles.index',
                        'permission' => '',
                        'icon' => '',
                        'label' => 'terminal_group_web_articles',
                        'target' => '',
                        'sort' => 600,
                        'status' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                        'children' => [],
                    ],
                ],
            ],
        ],
    ],
    [
        'name' => '插件',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-plug',
        'label' => 'plugins_group',
        'target' => '',
        'sort' => 1500,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '插件列表',
                'uri' => 'backend.plugins.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'plugins',
                'target' => '',
                'sort' => 1000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '模块',
        'uri' => '',
        'permission' => '',
        'icon' => 'fa fa-fw fa-cubes',
        'label' => 'modules_group',
        'target' => '',
        'sort' => 1000,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
        'children' => [
            [
                'name' => '模块列表',
                'uri' => 'backend.modules.index',
                'permission' => '',
                'icon' => '',
                'parent_id' => '',
                'label' => 'modules',
                'target' => '',
                'sort' => 100000,
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ],
    ],
    [
        'name' => '应用市场',
        'uri' => 'backend.applications.index',
        'permission' => '',
        'icon' => 'fa iconfont icon-application',
        'label' => 'applications_group',
        'target' => '',
        'sort' => 800,
        'status' => true,
        'created_at' => now(),
        'updated_at' => now(),
    ],
];
