<?php

$guard_name = 'admin';
$administrator = config('systems.security.administrator', 'Administrator');

return [
    'roles' => [
        [
            'name' => $administrator,
            'guard_name' => $guard_name,
            'group' => '系统管理员',
            'title' => '超级管理员',
            'description' => '具有最高权限，拥有所有系统权限',
            'sort' => 1000,
            'status' => true,
            'permissions' => [],
        ], [
            'name' => 'Admin',
            'guard_name' => $guard_name,
            'group' => '系统管理员',
            'title' => '管理员',
            'description' => '具有仅次于超级管理员权限，拥有系统大部分权限',
            'sort' => 1000,
            'status' => true,
            'permissions' => [],
        ],
    ],
    'permissions' => [
        [
            'name' => 'System\Http\Controllers\Backend\Systems\BasesController@index',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-基本设置-查看',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\BasesController@store',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-基本设置-修改',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\DataBasesController@index',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-数据库设置-查看',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\DataBasesController@store',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-数据库设置-修改',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\RoutesController@index',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-路由设置-查看',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\RoutesController@store',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-路由设置-修改',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\MenusController@index',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-菜单设置-查看',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\MenusController@create',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-菜单设置-添加',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\MenusController@update',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-菜单设置-修改',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\MenusController@destroy',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-菜单设置-删除',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\AdminsController@index',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-权限管理-管理员-查看',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\AdminsController@create',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-权限管理-管理员-添加',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\AdminsController@update',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-权限管理-管理员-修改',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\AdminsController@destroy',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-权限管理-管理员-删除',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\SecurityController@index',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-安全设置-查看',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ], [
            'name' => 'System\Http\Controllers\Backend\Systems\SecurityController@update',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-安全设置-修改',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ],[
            'name' => 'Laravel\Telescope\Http\Controllers',
            'guard_name' => $guard_name,
            'group' => '系统管理',
            'title' => '系统-系统监控',
            'description' => '',
            'sort' => 1000,
            'status' => true,
            'role' => $administrator,
        ],
    ],
];
